USE [master]
GO

/****** Object:  Database [TekusClientsDB]    Script Date: 15/06/2020 12:09:40 p. m. ******/
DROP DATABASE [TekusClientsDB]
GO

/****** Object:  Database [TekusClientsDB]    Script Date: 15/06/2020 12:09:40 p. m. ******/
CREATE DATABASE [TekusClientsDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TekusClientsDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS01\MSSQL\DATA\TekusClientsDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TekusClientsDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS01\MSSQL\DATA\TekusClientsDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TekusClientsDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TekusClientsDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TekusClientsDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TekusClientsDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TekusClientsDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TekusClientsDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [TekusClientsDB] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [TekusClientsDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TekusClientsDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TekusClientsDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TekusClientsDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TekusClientsDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TekusClientsDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TekusClientsDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TekusClientsDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TekusClientsDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [TekusClientsDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TekusClientsDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TekusClientsDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TekusClientsDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TekusClientsDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TekusClientsDB] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [TekusClientsDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TekusClientsDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TekusClientsDB] SET  MULTI_USER 
GO

ALTER DATABASE [TekusClientsDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TekusClientsDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TekusClientsDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TekusClientsDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TekusClientsDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TekusClientsDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TekusClientsDB] SET  READ_WRITE 
GO


