insert into Clients (Name, Email, nit) values ('Importaciones Tekus','importaciones@tekus.com','8008756-3');
insert into Clients (Name, Email, nit) values ('SpaceZ','ilomosk@spacez.com','90012156-3');
insert into Clients (Name, Email, nit) values ('Nikola','ilonmosk@nikola.com','80389756-3');
insert into Clients (Name, Email, nit) values ('Macrosoft','bussiness@macrosoft.com','50356512-3');
insert into Clients (Name, Email, nit) values ('Mike','contact@mike.com','80389756-3');
insert into Clients (Name, Email, nit) values ('Orange','orange@orange.com','80389756-3');
insert into Clients (Name, Email, nit) values ('Nokia','ilonmosk@nikola.com','80389756-3');
insert into Clients (Name, Email, nit) values ('Claro','ilonmosk@nikola.com','80389756-3');
insert into Clients (Name, Email, nit) values ('adidas','adidas@adidas.com','80389756-3');
insert into Clients (Name, Email, nit) values ('HP','ilonmosk@nikola.com','80389756-3');
insert into Services (Name, Price, ProviderId) values ('Descarga espacial de contenidos', 200, 1);
insert into Services (Name, Price, ProviderId) values ('Desaparacion forzada de bytes', 999.99, 1);
insert into Services (Name, Price, ProviderId) values ('Misiones espaciales', 2000000000, 2);
insert into Services (Name, Price, ProviderId) values ('Tour a Marte', 10000000000, 2);
insert into Services (Name, Price, ProviderId) values ('Venta de autos electricos', 2000, 3);
insert into Services (Name, Price, ProviderId) values ('Sistema operativo Door 12', 125, 4);
insert into Services (Name, Price, ProviderId) values ('Zapatos', 50, 5);
insert into Services (Name, Price, ProviderId) values ('Venta de Telefonos con camaras muy potentes', 1100, 6);
insert into Services (Name, Price, ProviderId) values ('Venta de Tablets', 1000, 6);
insert into Services (Name, Price, ProviderId) values ('Venta de telefonos que rompen el suelo', 500, 7);
insert into Services (Name, Price, ProviderId) values ('Operador de celular', 50, 8);
insert into Services (Name, Price, ProviderId) values ('Venta de zapatos', 200, 9);
insert into Services (Name, Price, ProviderId) values ('Computadores', 1000, 10);
insert into Countries(Name) values ('Colombia');
insert into Countries(Name) values ('Mexico');
insert into Countries(Name) values ('Peru');
insert into Countries(Name) values ('Estados Unidos');
insert into Countries(Name) values ('Argentina');
insert into Countries(Name) values ('Chile');
insert into Countries(Name) values ('Uruguay');
insert into Countries(Name) values ('Costa Rica');
insert into Countries(Name) values ('Canada');
insert into Countries(Name) values ('Ecuador');
insert into ServiceCountries (ServiceId, CountryId) values (1, 1);
insert into ServiceCountries (ServiceId, CountryId) values (1, 2);
insert into ServiceCountries (ServiceId, CountryId) values (1, 3);
insert into ServiceCountries (ServiceId, CountryId) values (2, 1);
insert into ServiceCountries (ServiceId, CountryId) values (2, 2);
insert into ServiceCountries (ServiceId, CountryId) values (2, 3);
insert into ServiceCountries (ServiceId, CountryId) values (3, 4);
insert into ServiceCountries (ServiceId, CountryId) values (3, 2);
insert into ServiceCountries (ServiceId, CountryId) values (4, 4);
insert into ServiceCountries (ServiceId, CountryId) values (5, 4);
insert into ServiceCountries (ServiceId, CountryId) values (6, 1);
insert into ServiceCountries (ServiceId, CountryId) values (6, 5);
insert into ServiceCountries (ServiceId, CountryId) values (6, 9);
insert into ServiceCountries (ServiceId, CountryId) values (6, 10);
insert into ServiceCountries (ServiceId, CountryId) values (7, 2);
insert into ServiceCountries (ServiceId, CountryId) values (7, 7);
insert into ServiceCountries (ServiceId, CountryId) values (7, 8);
insert into ServiceCountries (ServiceId, CountryId) values (8, 9);
insert into ServiceCountries (ServiceId, CountryId) values (8, 3);
insert into ServiceCountries (ServiceId, CountryId) values (8, 5);
insert into ServiceCountries (ServiceId, CountryId) values (8, 6);
insert into ServiceCountries (ServiceId, CountryId) values (8, 7);
insert into ServiceCountries (ServiceId, CountryId) values (9, 5);
insert into ServiceCountries (ServiceId, CountryId) values (9, 6);
insert into ServiceCountries (ServiceId, CountryId) values (10, 1);
insert into ServiceCountries (ServiceId, CountryId) values (10, 5);
insert into ServiceCountries (ServiceId, CountryId) values (10, 10);